services:
  - type: web
    name: pizzaria-rural-backend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        fromDatabase:
          name: pizzaria-rural-db
          property: connectionString

databases:
  - name: pizzaria-rural-db
    plan: free
    postgresMajorVersion: 15
